### ISSUE TITLE
U2 AutoPerks breaks on Max Tenacity

### ISSUE THREAD

**Issue by esposc** [Zorn192/AutoTrimps#108]
Allocating more than max tenacity can cause autoperks to leave all tenacity unassigned

![AT_1](https://user-images.githubusercontent.com/27485593/73453817-cb86e180-433a-11ea-81c8-04256d487aa2.png)
vs.
![AT_2](https://user-images.githubusercontent.com/27485593/73453833-d3df1c80-433a-11ea-91cf-edd566fa86e3.png)

**Comment by nkilio1991** [comment]
#108 Tenacity change fixedPerk is wrong
