### ISSUE TITLE
Script dont fight

### ISSUE THREAD

**Issue by greg4711** [Zorn192/AutoTrimps#118]
AutoTrimp has not been working properly for two days. AutoPortal and VoidMaps are running, but Fight is no longer executed automatically. Tried different machines, Firefox, Chrome, Greasemonkey and Tampermonkey, same everywhere.

Does anyone have an idea what this could be due to?

**Comment by xAhlen** [comment]
I have the same problem, have to click fight after a portal

**Comment by Adam-Edry** [comment]
I ran into something similar now. Go to the Combat & Stance settings, above Fight Always there should be options, by default they are hidden and you only see a black line. Click on the black line and you will see options that should solve your problem. I put it on vanilla.

**Comment by greg4711** [comment]
thanks i found it, now it runs again.

 
 

Gesendet: Montag, 21. September 2020 um 00:10 Uhr
Von: "Adam-Edry" <notifications@github.com>
An: "Zorn192/AutoTrimps" <AutoTrimps@noreply.github.com>
Cc: "greg4711" <haraldonline@gmx.de>, "Author" <author@noreply.github.com>
Betreff: Re: [Zorn192/AutoTrimps] Script dont fight (#118)


 

I ran into something similar now. Go to the Combat & Stance settings, above Fight Always there should be options, by default they are hidden and you only see a black line. Click on the black line and you will see options that should solve your problem. I put it on vanilla.
