### ISSUE TITLE
Tribute farming not triggering

### ISSUE THREAD

**Issue by niril** [Zorn192/AutoTrimps#134]
After the split of TimeFarming and TributeFarming, I have not been able to get Tribute farming to work. I've reset AutoTrimps to defaults and tried from scratch, but it will still not trigger.
I believe the root of this problem is line 1046 in maps:

Rtimefarm = (getPageSetting('Rtimefarm') == true && ((timefarmcell <= 1) || (timefarmcell > 1 && (game.global.lastClearedCell + 1) >= timefarmcell)) && game.global.world > 5 && (game.global.challengeActive != "Daily" && getPageSetting('Rtimefarmzone')[0] > 0 && getPageSetting('Rtimefarmtime')[0] > 0));

This has to be true to trigger TributeFarming in the following line. However, as far as I can see, it is a direct copy from TimeFarming and hence uses TimeFarming inputs, which are not available for tribute farming.

I hope this is not an error on my end, but i believe this line is in error :-)

**Comment by Zorn192** [comment]
should be fixed, let me know if it isnt
