### ISSUE TITLE
Steam version crashes as soon as the autotrimps splash screen shows up when starting.

### ISSUE THREAD

**Issue by itstwoam** [Zorn192/AutoTrimps#149]
Started last night after rebooting from a power loss.  The game itself will come up but as soon as mod.js is placed in the mods folder and that splash screen comes up the crash happens.  I've nuked the Trimps folder and downloaded everything like new but there's been no change.  Seems to work in the web version without issue.  Exported the steam version to the web and there were no issues there.

**Comment by Zorn192** [comment]
That might be very difficult to solve unfortunately due to no console on steam, however it does work for me on steam with no issues

**Comment by itstwoam** [comment]
It must have been something on my end because after another reboot things seemed to be working right but the recent update has introduced another bug which I'll do a separate issue for.
