### ISSUE TITLE
Hypothermia - Storage setting broken

### ISSUE THREAD

**Issue by Malthanis** [Zorn192/AutoTrimps#151]
The M@Z-like update to Hypothermia challenge settings seems to have broken the 'storage' option. Sheds are being bought outside of Bonfire farming levels.

**Comment by Malthanis** [comment]
Some bug testing done, seems that the Hypo-specific Storage option is tied to the AutoBuilding suite of options being enabled (I had disabled it in favor of the in-game AutoStructure recently).

So I'd say either mention in the tooltip of HypoStorage that AutoBuildings is required (the easiest fix, I would think), or unlink it from AutoBuildings entirely.

**Comment by Zorn192** [comment]
you best believe i went with the easier option, but yeah I thought this was a given.
