### ISSUE TITLE
c2 runner runs void maps when No VMs is set

### ISSUE THREAD

**Issue by bleything** [Zorn192/AutoTrimps#152]
I'm trying to use the C2 runner. I have "No VMs" set but it's running them anyway and getting bogged down or stuck. Is there another setting that overrides this one?

[here's my config](https://gist.github.com/bleything/e367a71d6ac56edffd625edac3ae5487) if that's useful

**Comment by Zorn192** [comment]
Let me try a small fix, let me know if it works
