### ISSUE TITLE
Miscalculation of 'want n times more damage/health' when map cut off is <1

### ISSUE THREAD

**Issue by jgordon510** [Zorn192/AutoTrimps#159]
When the map cut off setting, under Maps settings is set to a cut off of < 1, Autotrimps calculates the wrong number in the 'want n times more damage/health' text.  

For example, if the setting is 0.20, and the current H:D ratio is 0.40, it will say 'want 0.40x more damage'.  I would think it would say '2x' more damage, in this case.  At any rate, the current text indicates that it's aiming for less damage, which is obviously not the intent.

**Comment by Zorn192** [comment]
I think i wrote that with the intention that you wouldnt use less than 1
