### ISSUE TITLE
Suggestion: include a default value for the gear prestige dropdown setting

### ISSUE THREAD

**Issue by jgordon510** [Zorn192/AutoTrimps#161]
The tooltip for the prestige setting in the Gear - Equipment Settings includes a note that it "should probably always be on something", and yet it is disabled by default. 

I'd like to suggest that it be set a couple of notches down the list by default.  This would have greatly improved my initial experience with AutoTrimps.

**Comment by Zorn192** [comment]
Er pretty sure this things been broken since i took over fork, had no luck fixing it in 5 years, my bad
