### ISSUE TITLE
Housing Borders Update Error in Time Lapse Mode 

### ISSUE THREAD

**Issue by KeinNiemand** [Zorn192/AutoTrimps#167]
Auto Trimps tries to update the the border color for housing when in time lapse, but those buttons/borders don't exist while in time lapse to it throws and error and get's stuck.
I repetitly get this error in the console while in time lapse.
19buildings.js:79 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at buyFoodEfficientHousing (buildings.js:79:56)
    at buyBuildings (buildings.js:169:5)
    at mainLoop (AutoTrimps2.js:196:13)
The same thing may or may not be happening with gear or other border colores it tries to update.
To fix this AT needs to check if the game is in time lapse/catching up lost time and stop updating borders.

**Comment by KeinNiemand** [comment]
After some further testing and debugging this error I've found out that this error only happens when a new housing is unlocked while time time lapse/offline mode. While the GUI elements for housing that's already unlocked is already loaded, the UI elements for Newley unlocked housing are undefined if they have been unlocked while in time lapse. This may or may not also be the case for equipment/upgrades/other stuff.

**Comment by KeinNiemand** [comment]
Also there a check in AutoTrimps2.js that disables equipment buying when in time lapse/offline progress mode. This might have been added because of issue here so by checking for usingRealTimeOffline before updating any borders or colors for housing/upgrades/equipment you could also enable equimpent buying during time lapse.
I've made a PR for rays version that fixes this (becouse that's the verson I'm using right now). If I ever get to the point in the game where switching to this version makes sense I'll make a PR for this version assuming it hasn't been fixed by then.

**Comment by Zorn192** [comment]
AT is not designed for timewarp my bad
