### ISSUE TITLE
(Early Game) Trap Trimps not working. Stuck on researching science

### ISSUE THREAD

**Issue by Celz22** [Zorn192/AutoTrimps#175]
I'm on world 21 now (new player) and the script never boosts trimp breeding speed if I die. It's just stuck on researching science. It doesn't even use Turkimp for metal etc.

Trap Trimps is enabled, Auto Gather/Build is also enabled, what is going on? I'm on steam btw

**Comment by Zorn192** [comment]
Fixed in autogather update (hopefully)
