### ISSUE TITLE
Auto Gather/Build stopped working today

### ISSUE THREAD

**Issue by PatomanGit** [Zorn192/AutoTrimps#177]
With Setting "Auto Gather/Build" enabled AT will only Upgrade Equipment. But no more gathering, building, job allocation or upgrades are done automatically. By Setting it to "Mining/Building Only" all works like it used to be but it is a little annoying since I have to manually do a few clicks after every portal. It defeats the purpose of AutoPortal for me.

Yesterday everything worked like a charm with "Auto Gather/Build". Any tips on how to fix my issue? I already reset my mods and settings. Restarted the game a few times but nothing fixed the above issue.

P.S. I am running AT on the Steam Version

**Comment by Zorn192** [comment]
Works now
