### ISSUE TITLE
Graphs not showing anymore 

### ISSUE THREAD

**Issue by pmaguire13** [Zorn192/AutoTrimps#183]
**EDIT:** I forgot to mention this is for the Steam version of the game

I am not sure exactly when it happened but probably when Trimps updated to 5.8.1

Where the graphs would show is completely blank (see image). 

![no graphs](https://user-images.githubusercontent.com/22167758/217155651-757f132a-8af3-4eb5-9209-4dbefdbfc349.png)

Also adding to this clicking the discord link (at least for the auto-trimps dev discord) in the auto-trimps start popup thing kind of softlocks the game by opening the discord link and staying on the discord page (at least if you decide to not join the discord, I am not sure if this happens if you do join). I couldn't even close the game traditionally, I had to stop the game from steam.

**EDIT:** I forgot to mention this is for the Steam version of the game

**Comment by Quiaaaa** [comment]
Potentially stupid question: Have you tried selecting a graph?

**Comment by pmaguire13** [comment]
I could have sworn I did try and it didn't work, but I tried just now and it worked... thank you
