### ISSUE TITLE
enoughDamage and enoughHealth stuck at true

### ISSUE THREAD

**Issue by ben831** [Zorn192/AutoTrimps#60]
Hi,

Since a day or 2 ago, the enoughDamage and enoughHealth flags are stuck at true regardless of the HD ratio for me.

Save and AT config attached.  Thanks.

[save.txt](https://github.com/Zorn192/AutoTrimps/files/3230937/save.txt)
[atconfig.txt](https://github.com/Zorn192/AutoTrimps/files/3230938/atconfig.txt)

**Comment by Zorn192** [comment]
Was fixed
