### ISSUE TITLE
C2 Runner

### ISSUE THREAD

**Issue by Wolf694** [Zorn192/AutoTrimps#61]
I have a problem, after i tried to let it do C2 challanges it got stuck and i dont know if i can "alter" the options without having to run  it.

It goes automatic into the Portal screen and wont let me push any button or neither I'm able to alter the options inside of trimps as the Options are below the Protal screen

![2019-06-04 15_45_13-Play Trimps, a free online game on Kongregate](https://user-images.githubusercontent.com/51372074/58884030-dfad0d00-86df-11e9-9312-14bce4e33938.png)

Is there any possibillity to fix this ?

**Comment by Zorn192** [comment]
Answered in Discord
