### ISSUE TITLE
Bug with AutoMaps logic in early game

### ISSUE THREAD

**Issue by tdietrich513** [Zorn192/AutoTrimps#63]
If explorers aren't available yet, and we don't have enough fragments to buy a map, AutoMaps will endlessly farm the level -1 map. This has happened to me twice on level 8. 

Should add a check that explorers are available before triggering the "run level -1 map and wait for fragments" logic.

**Comment by zsaur192** [comment]
AT isn't for early game so its not surprising you will run into issues. If you want to make a PR for this feel free, but my priority is currently U2.

-Zek's beta Account
