### ISSUE TITLE
[5.0.0] game.talents.turkimp4 is undefined

### ISSUE THREAD

**Issue by johanvanhelden** [Zorn192/AutoTrimps#64]
In version 5.0.0, `game.talents.turkimp4` does no longer exist. There is however a `game.talents.turkimp` and `game.talents.turkimp2`, but I am not sure what it _should_ be. So I am unsure what a PR fix should look like.

Maybe more things are broken due to the 5.0.0 update, but this is why my buildings are no longer automatically upgraded.

**Comment by JackTerok** [comment]
![Turkimp](https://user-images.githubusercontent.com/10469129/62445920-c0734000-b761-11e9-846c-9ef57da5eaba.jpg)

**Comment by johanvanhelden** [comment]
A superhacky workaround for people who want to use AT until it's fixed, you can enter in your browser's console:

`game.talents.turkimp4 = false` 

And now auto-buying works again for me.

**Comment by johanvanhelden** [comment]
Fixed with the new update, thanks @Zorn192!
