### ISSUE TITLE
Trimps not fighting

### ISSUE THREAD

**Issue by TimJones** [Zorn192/AutoTrimps#65]
Just updated to Trimps v5.0.0 and AutoTrimps v4.0.0 and my trimps no longer automatically fight. I can set them to fight manually, but if I toggle AutoFight on they start fighting but AutoTrimps immaculately toggles it back off.
My console is filled with the error `RerenceError: getPotencyMod is not defined`.

**Comment by Zorn192** [comment]
Could you tell me the whole error

**Comment by TimJones** [comment]
I uploaded my console log to https://gist.github.com/TimJones/ddfca5f3e027f33531b665ffac0d4b69

The specific error that is constantly counting up with every tick is the following:
```
ReferenceError: getPotencyMod is not defined1301 fight.js:32:22
    betterAutoFight2 https://zorn192.github.io/AutoTrimps/modules/fight.js:32
    mainLoop https://zorn192.github.io/AutoTrimps/AutoTrimps2.js:225
```

**Comment by TimJones** [comment]
To add, I noticed that if I change the combat settings to use either BAF1 or BAF3 then autofighting works.

**Comment by Zorn192** [comment]
I added a fix last night, let me know if it works now

**Comment by toaran** [comment]
BAF2 is now gone... is BAF1 now to go to setting?

**Comment by Zorn192** [comment]
BAF1 is autotrimps autofight
vanilla is vanilla autofight but with a little bonus to make sure its fighting at z1 and such
BAF2 was completely broken

I use vanilla.

**Comment by TimJones** [comment]
Just to confirm, with the removal of BAF2, autofights (BAF1 & 3) work without issue.
