### ISSUE TITLE
Typo for dmap5

### ISSUE THREAD

**Issue by gboomgaard** [Zorn192/AutoTrimps#71]
Hello,

With regards to the following:

https://github.com/Zorn192/AutoTrimps/blob/5996d49a3767818ad58db493ca681cdb44278e02/modules/other.js#L1589

It looks like !ddmapbought5 was mistakenly typed, I believe !dmapbought5 was intented.

Thank you.

**Comment by Zorn192** [comment]
Thanks, done, but feel free to do a PR for something like this in the future if you want :)
