### ISSUE TITLE
No AutoFight option

### ISSUE THREAD

**Issue by FelicitusNeko** [Zorn192/AutoTrimps#72]
AutoFight is not present in my copy of AutoTrimps. Where the button should be, there is just no button at all. It was there before. There is no error in the console. I have tried resetting AutoTrimps, to no avail.

Trimps ver 5.1.0
AutoTrimps-Zek ver 4.1.0

**Comment by Zorn192** [comment]
If you're not on dark theme, you may see a tiny thin black bar in combat, click it.
