### ISSUE TITLE
Enabling "Trap Trimps" gets You stuck Trapping (Checking Traps) forever

### ISSUE THREAD

**Issue by viology** [Zorn192/AutoTrimps#77]
When I have "Trap Trimps" setting enabled, it does nothing but check traps until there are <5 traps, then it will make a trap and check it etc. If it is disabled, upon portaling/auto-portaling, the game waits forever for a trimp that will never come.

**Comment by ZeroCool940711** [comment]
I got a similar issue, I noticed that now when I have "Trap Trimps" enabled autotrimps gets stuck after a portal, it doesn't click on "Gather" or "Chop" to get the 10 of each that you need to build the first trap, it just stays stuck there doing nothing, forever, if I click on gather and chop manually once I get 10 of each autotrimps starts working normally until the next portal where it again gets stuck.

**Comment by shatteredeagle** [comment]
Having the exact same issue as @ZeroCool940711. Have to kickstart the run every time it auto portals by gathering the 10 food/wood.
