### ISSUE TITLE
Small problem with the Heirloom code

### ISSUE THREAD

**Issue by ausonny** [Zorn192/AutoTrimps#91]
The code is checking slot5modst and stot5modsh twice and not checking the slot6mods.
I don't have the ability to create a pull request at the moment, or I would put one up, sorry.

function getHeirloomEff(name, type) {
  if (type == "staff") {
    if (getPageSetting('slot1modst') == name) return 6;
    else if (getPageSetting('slot2modst') == name) return 5;
    else if (getPageSetting('slot3modst') == name) return 4;
    else if (getPageSetting('slot4modst') == name) return 3;
    else if (getPageSetting('slot5modst') == name) return 2;
    else if (getPageSetting('slot5modst') == name) return 1;
	else return 0;
  }
  else if (type == "shield") {
    if (getPageSetting('slot1modsh') == name) return 6;
    else if (getPageSetting('slot2modsh') == name) return 5;
    else if (getPageSetting('slot3modsh') == name) return 4;
    else if (getPageSetting('slot4modsh') == name) return 3;
    else if (getPageSetting('slot5modsh') == name) return 2;
    else if (getPageSetting('slot5modsh') == name) return 1;
	else return 0;

**Comment by Zorn192** [comment]
Done and thanks
