### ISSUE TITLE
Prestige setting turns off on reload of page

### ISSUE THREAD

**Issue by ausonny** [Zorn192/AutoTrimps#93]
When I reload the trimps page the prestige setting under the Gear tab in autotrimps(i.e. Dagadder, Helishmet, GambesOP etc.) changes to Off.  It's the only thing I've noticed that doesn't reload as I had set it.  Is this intended?

**Comment by ausonny** [comment]
Asking if it was intentional was silly, I only asked because I figured I couldn't be the only person to notice it.  I have noticed that changing the Prestige setting does not update the local storage.  Changing anything else does save the Prestige setting to local storage, but no matter what it is set to, upon reloading the page the setting is always set to off.  I can't find the issue in the code, it all looks like it should work to me.

**Comment by Zorn192** [comment]
Yeah im also having an issue with it, it might be getting set to none somewhere else in the code
