### ISSUE TITLE
Catch error when using auto-heirloom on <6 slot Heirlooms

### ISSUE THREAD

**Issue by TheKleopiNetwork** [Zorn192/AutoTrimps#94]
Turns out many of the bugs i mentioned before are due to Auto-Heirlooms and Auto-Nu being enabled and throwing hidden errors.

Found those errors in console and noticed:
AutoPortal was completely disfunctional #81 
C2 Runner didnt run
Autofight turning off randomly
- other smaller bugs

Maybe just add a check on that setting so it checks whether the Heirloom has 6 slots or not, and just either adapt the routine to use less slots, or ignore the routine. This setting should not cause the whole script to break, when set by accident

**Comment by Zorn192** [comment]
Its mainly due to autonu, ill disable it and remove the option to use it. Its not really worth my time to update it now, unless someone fancies fixing it. Closing as im disabling autonu
