### ISSUE TITLE
C2 Runner gets stuck if challenge is not unlocked

### ISSUE THREAD

**Issue by OrenAudeles** [Zorn192/AutoTrimps#95]
Possible relation to #61 

### Problem Description
When using `C2 Runner` with HZE 175 got stuck attempting to run the `Watch` C2 which is not unlocked yet. `Watch` unlocks at Z180. Will probably get stuck again for any other C2 where the challenge is unlocked at a higher than HZE zone.

### Possible solution
Add check that the challenge is unlocked using a mapping between the Challenge name and its unlock zone. Eg. `"Watch" : 180`, `"Lead" : 180`.

EG: 
https://github.com/Zorn192/AutoTrimps/blob/1bfc70c6835b271c7981fa5b5eac870d89efb561/modules/portal.js#L152-L156

to

```js
if( challenge_unlocked( "Size" ) && should_run_c2( game.c2.Size ) ) {
   [...]
}
```
where `challenge_unlocked` is along the lines of
```js
function challenge_unlocked( challenge_name ) {
    return ( game.global.highestLevelCleared+1 ) >= challenge_unlock_zones[ challenge_name ];
}
```
and `should_run_c2` the current condition, split off to its own function for readability purposes
```js
function should_run_c2( c2_val ) {
    return (100*( c2_val /(game.global.highestLevelCleared+1))) < getPageSetting('c2runnerpercent')
}
```

**Comment by OrenAudeles** [comment]
My current workaround, as I don't have Watch or Lead unlocked, is to add `false &&` at the start of their conditions.
```js
if( false && 
    (100*(game.c2.<challenge>/(game.global.highestLevelCleared+1))) < getPageSetting('c2runnerpercent') ) {
[...]
}
```

**Comment by Zorn192** [comment]
I added a check if challenge is completed

**Comment by OrenAudeles** [comment]
Awesome, thanks for the fast resolution :D
